/*
 * GLOBAL / GENERAL RISK ASSESSMENT LIBRARY
 * =========================================
 * Editable static library of complete generic RAs, one category per RA.
 * Picking a category in "Add from General RA Library" adds all its items.
 * Plain data - nothing else in the app needs to change when you edit it.
 *
 * Item shape (same as a manually-entered risk item):
 *   hazard, effect, ctrl -> { en, ar }   (multiple lines separated by \n)
 *   severityBefore (1-5), likelihoodBefore (A-E)  - Free Analysis
 *   severityAfter (1-5), likelihoodAfter (A-E)    - Controlled Analysis
 * Evaluation is calculated from the controlled code via matrix.js.
 *
 * Source: Rashpetco Risk Assessment Proformas (controlled copies), 2026-10.
 * "Use of Hand Tools" keeps its earlier conversion (its proforma uses the
 * old numeric 1-6 scale, not 1-5 / A-E).
 * Arabic (`ar`) is blank - use "Auto-translate All to Arabic" after adding,
 * and review the result.
 */

const GLOBAL_RA_LIBRARY = [
  {
    category: { en: "Use of Electrical Power Hand Tools", ar: "استخدام العدد الكهربائية اليدوية" },
    items: [
      {
        hazard: { en: "Use of Electric Hand Power Tools.", ar: '' },
        effect: { en: "Possible fatality.\nFire and Explosion.\nAsset damage.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'B',
        ctrl: { en: "Only competent persons to use electric hand power tools.\nOnly electric hand power tools that have been certified and test approved to be allowed on site.\nAll Electric hand power tools to be registered in the Temporary Equipment Log Book.\nCertification documents to be in safe keeping with the Supervisor.\nTool Box Talk.\nContinuous gas monitoring.\nFire equipment available and ready for use.\nBarriers and warning signs to be erected in area of work.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Electric Hand Power Tools not fit for purpose.", ar: '' },
        effect: { en: "Possible fatality.\nFire and Explosion.\nAsset damage.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Only competent persons to use electric hand power tools.\nOnly certified electric hand power tools to be used.\nOnly electric hand power tools suitable for the task to be used.\nElectric hand power tools to be checked by the Performing Authority prior to start of work.\nCorrect PPE suitable for task to be worn at all times.\nTool Box Talk.\nContinuous gas monitoring during task.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Electric Hand Power Tool cables.", ar: '' },
        effect: { en: "Major injury.\nInjury to personnel caused by slips / trips / falls.\nElectric shock.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'B',
        ctrl: { en: "Only competent persons to use electric hand power tools.\nCables to be routed away from normal access / walkway areas.\nCables to be checked for signs of wear and damage and defective tools not to be used.\nCables to be kept clear of any water deposits.\nTool Box Talk.\nBarriers and warning signs to be erected where applicable.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Noise from electric hand power tools.", ar: '' },
        effect: { en: "Hearing loss.", ar: '' },
        severityBefore: 1, likelihoodBefore: 'C',
        ctrl: { en: "Only competent persons to use electric hand power tools.\nWhere possible noise survey to be carried out to assess decibel levels of electric power tools in use.\nPersonnel to wear ear defenders or ear plugs at all times when power tools are in use.", ar: '' },
        severityAfter: 1, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Noise from process plant equipment.", ar: '' },
        effect: { en: "Hearing loss.", ar: '' },
        severityBefore: 1, likelihoodBefore: 'C',
        ctrl: { en: "Ear protection to be worn at all times in areas of high noise levels.\nAdhere to warning signs in areas of noise on plant.", ar: '' },
        severityAfter: 1, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Overload.\nMechanical failure.", ar: '' },
        effect: { en: "Major injury.\nDamage to equipment.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'B',
        ctrl: { en: "Pre-checks to be carried out.\nSuitable fire extinguisher available on site.\nAdequate supervision.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Hand and power tools slippage / movement failure.", ar: '' },
        effect: { en: "Major injury from debris, falling objects, crushing, trapping.\nEquipment damage.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'B',
        ctrl: { en: "Suitable PPE to be used e.g. gloves, goggles.\nAdequate supervision.\nTool Box Talk prior to start of work.\nCheck tools / equipment before and during use.\nQuality tools only to be used.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Manual handling.", ar: '' },
        effect: { en: "Injuries due to lifting, lowering, carrying, pushing, pulling.", ar: '' },
        severityBefore: 1, likelihoodBefore: 'A',
        ctrl: { en: "Using safe working methods in carrying out the job.\nUse of proper hand tools.\nUse of proper lifting equipment.\nWear correct PPE.", ar: '' },
        severityAfter: 1, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Cuts and abrasions.", ar: '' },
        effect: { en: "Injury from sharp edges, debris, flying particles.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'A',
        ctrl: { en: "Suitable PPE to be used e.g. gloves, goggles.\nToolbox talk prior to starting work.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Plant emergency (all personnel to muster).", ar: '' },
        effect: { en: "Serious injury to personnel.\nSlips / Trips / Falls.", ar: '' },
        severityBefore: 1, likelihoodBefore: 'B',
        ctrl: { en: "Personnel are to make safe their worksite by de-energizing / depressurizing equipment in use.\nPersonnel are then to make their way to muster in an orderly manner.", ar: '' },
        severityAfter: 1, likelihoodAfter: 'A',
      },
    ],
  },
  {
    category: { en: "Use of Pneumatic Power Tools", ar: "استخدام العدد الهوائية" },
    items: [
      {
        hazard: { en: "Use of Pneumatic Power Tools.", ar: '' },
        effect: { en: "Possible injury to personnel.\nDamage to equipment.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'B',
        ctrl: { en: "Only competent persons to use Pneumatic power tools.\nOnly Pneumatic power tools that have been certified and test approved to be allowed on site.\nAll Pneumatic power tools to be registered in the Temporary Equipment Log Book.\nCertification documents to be in safe keeping with the Supervisor.\nTool Box Talk.\nCorrect PPE to be worn at all times.\nBarriers and warning signs to be erected in area of work.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Pneumatic Power Tools not fit for purpose.", ar: '' },
        effect: { en: "Injury to personnel.\nAsset damage.\nDamage to equipment.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Only competent persons to use Pneumatic power tools.\nOnly certified Pneumatic power tools to be used.\nOnly Pneumatic power tools suitable for the task to be used.\nPneumatic power tools to be checked by the Performing Authority prior to start of work.\nCorrect PPE suitable for task to be worn at all times.\nTool Box Talk.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Working at height.", ar: '' },
        effect: { en: "Major injury.\nPossible fatality.\nSlips / Trips / Falls.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Pneumatic power tool hoses: injury to personnel caused by slips / trips / falls.\nOnly competent persons to use Pneumatic power tools.\nHoses to be routed away from normal access / walkway areas.\nHoses to be checked for signs of wear and damage and defective tools not to be used.\nHoses to have whiplash connections.\nStored mechanical energy to be released from hoses during breaks / end of work day and prior to any cleaning of equipment / repairs.\nTool Box Talk.\nUse safe access and egress at all times.\nBarriers and warning signs to be erected where applicable.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Noise from Pneumatic power tools.", ar: '' },
        effect: { en: "Hearing loss.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Only competent persons to use Pneumatic power tools.\nWhere possible noise survey to be carried out to assess decibel levels of Pneumatic power tools in use.\nPersonnel to wear ear defenders or ear plugs at all times when power tools are in use.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Noise from process plant equipment.", ar: '' },
        effect: { en: "Hearing loss.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Ear protection to be worn at all times in areas of high noise levels.\nAdhere to warning signs in areas of noise on plant.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Manual handling.", ar: '' },
        effect: { en: "Serious injury to personnel.\nBack and limb strain.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Personnel to use correct kinetic manual handling techniques.\nUse safe access and egress at all times.\nUse correct PPE at all times.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Use of hand tools.", ar: '' },
        effect: { en: "Personal injury.\nDamage to equipment.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'B',
        ctrl: { en: "Only competent personnel to carry out the task.\nUse only certified hand tools.\nHand tools to be checked by Performing Authority prior to use.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Completion of task.", ar: '' },
        effect: { en: "Poor housekeeping.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'B',
        ctrl: { en: "Equipment to be correctly stored and removed from work area.\nArea to be kept clean and tidy at all times.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Site emergency.\nAll personnel to muster.", ar: '' },
        effect: { en: "Injury to personnel.\nSlips / Trips / Falls.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "All personnel are to make safe their equipment by de-energizing or de-pressurizing hoses prior to leaving worksite.\nPersonnel to report to their designated muster points in an orderly manner.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
    ],
  },
  {
    category: { en: 'Use of Hand Tools', ar: 'استخدام العدد اليدوية' },
    items: [
      {
        hazard: { en: 'Hand tools not fit for purpose.', ar: '' },
        effect: { en: 'Personal Injury.\nDamage to Equipment.', ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: 'Only competent personnel to carry out the task.\nTool Box Talk.\nAdequate supervision where required.\nOnly tools fit for the task to be used.\nCorrect PPE to be worn at all times.', ar: '' },
        severityAfter: 2, likelihoodAfter: 'B',
      },
      {
        hazard: { en: 'Damaged or badly worn tools.', ar: '' },
        effect: { en: 'Personal Injury.\nTrapped fingers and limbs.\nDamage to equipment.', ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: 'Only competent personnel to carry out the task.\nTools to be inspected on a regular basis.\nDamaged and badly worn tools to be discarded and replaced with new.', ar: '' },
        severityAfter: 2, likelihoodAfter: 'B',
      },
      {
        hazard: { en: 'Use of hand tools at height', ar: '' },
        effect: { en: 'Dropped objects.\nInjury to personnel.\nDamage to equipment.', ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: 'Only competent personnel to carry out the task.\nTools to be secured whilst lifting to area of work.\nUse correct manual handling techniques.\nLifting equipment to be inspected prior to operation.\nTools not being used at time to be kept secured in work area.', ar: '' },
        severityAfter: 3, likelihoodAfter: 'B',
      },
      {
        hazard: { en: 'Tools with poor housekeeping', ar: '' },
        effect: { en: 'Dropped objects.\nInjury to personnel.\nDamage to equipment.', ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: 'Tools to be kept clean and free from task product / oil / grease.\nTools to be checked during and after task.\nCompetent persons to carry non-chemical cleaning materials e.g rags / cloth.', ar: '' },
        severityAfter: 2, likelihoodAfter: 'B',
      },
      {
        hazard: { en: 'Tools not used on a regular basis.', ar: '' },
        effect: { en: 'Injury to personnel.\nDamage to equipment.\nTools failing in use.', ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: 'Tools to be well maintained by personnel while not in use.\nTools to be kept stored in a clean / dry area.\nRegular periodic checks to be carried out.', ar: '' },
        severityAfter: 2, likelihoodAfter: 'B',
      },
    ],
  },
  {
    category: { en: "Wash Cleaning by Using Diesel Fuel", ar: "الغسيل والتنظيف باستخدام السولار" },
    items: [
      {
        hazard: { en: "Static discharge.", ar: '' },
        effect: { en: "Flow of fuel through plastic hoses or non-bonded equipment can generate static electricity.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Use anti-static hoses.\nEnsure proper grounding and bonding of pump and system.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Heat ignition.", ar: '' },
        effect: { en: "Diesel vapors can ignite from pump motor, hot surfaces, or friction.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Ensure pump is ATEX-rated (explosion-proof).\nMaintain adequate ventilation.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Vapor accumulation.", ar: '' },
        effect: { en: "In enclosed or poorly ventilated areas, vapors can build up and ignite.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Operate in well-ventilated area or use vapor recovery system.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Use of non-intrinsically safe electrical equipment.", ar: '' },
        effect: { en: "Can lead to ignition of vapors.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Use explosion-proof rated equipment only (Zone classification as per ATEX or NEC).", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Vehicle collision / rollover.", ar: '' },
        effect: { en: "Can cause catastrophic fuel release and fire.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Use trained, licensed drivers.\nFollow designated routes.\nAvoid high-traffic areas.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Static discharge during transfer.", ar: '' },
        effect: { en: "Static buildup during filling / unloading can ignite vapors.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Ground and bond all vehicles, tanks, and hoses.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Equipment failure (pumps, hoses).", ar: '' },
        effect: { en: "Failure of transfer equipment causes fuel leaks.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Use certified equipment rated for diesel fuel.\nRoutine inspection and maintenance.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Environmental contamination.", ar: '' },
        effect: { en: "Diesel spill into soil, drains, or waterways during transit.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Use secondary containment (e.g. bunded tanks).\nAvoid drainage areas.\nReport spills promptly.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Spillage during loading / unloading.", ar: '' },
        effect: { en: "Hose failure, operator error, or overfilling may cause fuel spill.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Use trained personnel.\nEmploy automatic shutoff systems.\nInstall spill containment.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
    ],
  },
  {
    category: { en: "Water Wash for Gas-Turbine MC", ar: "الغسيل بالمياه لماكينة التوربين الغازي" },
    items: [
      {
        hazard: { en: "Fire suppressant disabled for entry into enclosure.", ar: '' },
        effect: { en: "Potential fire and explosion.\nPossible fatality.\nDamage to equipment.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Only competent personnel to carry out the task.\nRaise PSIC to inhibit Fire Protection system in enclosure prior to task.\nIsolation of Fire Protection system by local Hand/Auto switch in Generator.\nTool Box Talk.\nFire watch in attendance at all times during task to initiate Fire Protection system manual release in event of fire.\nUse correct PPE suitable for task at all times.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Activation of fire suppressant.", ar: '' },
        effect: { en: "Asphyxiation.\nPossible fatality.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Fire watch to ensure that all persons have evacuated the enclosure prior to initiating.\nFire watcher to maintain good communications at all times with entrants.\nOnly essential personnel to enter enclosure.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Access and egress to and from enclosure.", ar: '' },
        effect: { en: "Slips / Trips / Falls.\nSerious injury to personnel.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Only competent personnel to carry out the task.\nBe aware of potential trip hazards, pipe work / cables / equipment.\nTool Box Talk.\nAdequate lighting in enclosure.\nUse correct PPE suitable for task at all times.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Hot surfaces inside enclosure.", ar: '' },
        effect: { en: "Burns to exposed areas of skin.\nSerious injury.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Only trained and competent personnel to carry out the task.\nUse safe access and egress at all times.\nLong sleeve coveralls shall only be worn by entrants.\nCorrect PPE to be worn at all times whilst in enclosure.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Rotating and motive power.", ar: '' },
        effect: { en: "Possible fatality.\nMajor injury.\nDamage to equipment.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Only competent personnel to carry out the task.\nAll motive and rotating parts to be covered or guarded to prevent entanglement.\nNo guards or covers to be removed whilst machinery is in use.\nPersonnel not to wear loose clothing inside enclosure.\nPersonnel to keep as much distance as possible from moving parts.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Dropped objects by personnel.", ar: '' },
        effect: { en: "Damage to equipment.\nAsset damage.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Personnel advised to remove any loose objects from pockets prior to entering enclosure.\nAll tools (where applicable) are to be accounted for and checked on completion of task and removed from enclosure.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Noise from rotating equipment and machinery.", ar: '' },
        effect: { en: "Damage to hearing.\nHearing loss.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Personnel are advised to use ear defenders in noise levels in excess of 35 decibels.\nEar plugs are only of use in noise levels less than 35 decibels.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Housekeeping.", ar: '' },
        effect: { en: "Spillage / leakage from machinery.\nPoor housekeeping.\nEnvironmental.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "During inspection by personnel any leaks or spillages to be removed by suitable means from the enclosure.\nPersonnel to use suitable receptacles for disposal of waste materials.\nWaste materials to be removed from site by specialist company.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Site alarm.\nAll personnel to muster.", ar: '' },
        effect: { en: "Slips / Trips / Falls.\nSerious injury.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Personnel are to make safe their worksite prior to leaving area.\nFire watcher to ensure that all personnel have evacuated the enclosure and have been accounted for.\nPersonnel to make their way to the muster point in a safe and orderly manner.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
    ],
  },
  {
    category: { en: "Entry into Turbine Enclosure", ar: "الدخول إلى حاوية التوربين" },
    items: [
      {
        hazard: { en: "Fire suppressant disabled for entry into enclosure.", ar: '' },
        effect: { en: "Potential fire and explosion.\nPossible fatality.\nDamage to equipment.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Only competent personnel to carry out the task.\nRaise PSIC to inhibit Fire Protection system in enclosure prior to task.\nIsolation of Fire Protection system by local Hand/Auto switch in Generator.\nTool Box Talk.\nFire watch in attendance at all times during task to initiate Fire Protection system manual release in event of fire.\nUse correct PPE suitable for task at all times.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Activation of fire suppressant.", ar: '' },
        effect: { en: "Asphyxiation.\nPossible fatality.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Fire watch to ensure that all persons have evacuated the enclosure prior to initiating.\nFire watcher to maintain good communications at all times with entrants.\nOnly essential personnel to enter enclosure.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Access and egress to and from enclosure.", ar: '' },
        effect: { en: "Slips / Trips / Falls.\nSerious injury to personnel.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Only competent personnel to carry out the task.\nBe aware of potential trip hazards, pipe work / cables / equipment.\nTool Box Talk.\nAdequate lighting in enclosure.\nUse correct PPE suitable for task at all times.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Hot surfaces inside enclosure.", ar: '' },
        effect: { en: "Burns to exposed areas of skin.\nSerious injury.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Only trained and competent personnel to carry out the task.\nUse safe access and egress at all times.\nLong sleeve coveralls shall only be worn by entrants.\nCorrect PPE to be worn at all times whilst in enclosure.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Rotating and motive power.", ar: '' },
        effect: { en: "Possible fatality.\nMajor injury.\nDamage to equipment.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Only competent personnel to carry out the task.\nAll motive and rotating parts to be covered or guarded to prevent entanglement.\nNo guards or covers to be removed whilst machinery is in use.\nPersonnel not to wear loose clothing inside enclosure.\nPersonnel to keep as much distance as possible from moving parts.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Dropped objects by personnel.", ar: '' },
        effect: { en: "Damage to equipment.\nAsset damage.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Personnel advised to remove any loose objects from pockets prior to entering enclosure.\nAll tools (where applicable) are to be accounted for and checked on completion of task and removed from enclosure.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Noise from rotating equipment and machinery.", ar: '' },
        effect: { en: "Damage to hearing.\nHearing loss.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Personnel are advised to use ear defenders in noise levels in excess of 35 decibels.\nEar plugs are only of use in noise levels less than 35 decibels.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Housekeeping.", ar: '' },
        effect: { en: "Spillage / leakage from machinery.\nPoor housekeeping.\nEnvironmental.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "During inspection by personnel any leaks or spillages to be removed by suitable means from the enclosure.\nPersonnel to use suitable receptacles for disposal of waste materials.\nWaste materials to be removed from site by specialist company.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Site alarm.\nAll personnel to muster.", ar: '' },
        effect: { en: "Slips / Trips / Falls.\nSerious injury.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Personnel are to make safe their worksite prior to leaving area.\nFire watcher to ensure that all personnel have evacuated the enclosure and have been accounted for.\nPersonnel to make their way to the muster point in a safe and orderly manner.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
    ],
  },
  {
    category: { en: "Working at Heights", ar: "العمل على ارتفاعات" },
    items: [
      {
        hazard: { en: "Scaffolding / structure does not meet requirements.", ar: '' },
        effect: { en: "Possible fatality.\nDamage to equipment.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Scaffolding Supervisor to design structure fit for purpose.\nConformance with recognized codes and standards BS 5973:1993.\nOnly trained and competent personnel to erect scaffold platform.\nScaffolding Supervisor to discuss with PA the requirements of task.\nScaffold / structure to be erected on a solid foundation.\nSupervisor to identify and discuss with Performing Authority sensitive / vulnerable equipment which could be impacted with scaffolding activities.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Structure / platform not secured.", ar: '' },
        effect: { en: "Possible fatality.\nDamage to equipment.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Running boards and tubes to be correctly secured by means of clips or lashing.\nPerforming Authority to inspect and test scaffold prior to work activities.\nAny boards showing signs of wear or damage are not to be used.\nAny defective boards are to be replaced with new.\nSuitable handrails shall be fitted on all temporary platforms.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Access / egress restricted.", ar: '' },
        effect: { en: "Major injury.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Only trained and competent personnel to carry out the task.\nOnly personnel assigned to the task shall be on the platform.\nHoses and cables to be routed away from main access and egress points and secured.\nPersonnel to be aware of low fitting scaffolding poles and fixed structures.\nAccess and egress ladders to be fit for purpose and secured.\nCorrect PPE to be worn at all times.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Falling from height.", ar: '' },
        effect: { en: "Possible fatality.\nMajor injury.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Only trained and competent personnel to carry out tasks at height.\nOnly trained and competent personnel to wear a harness and inertia reel.\nWhen working at height of less than 5.6 meters, the use of a nano-lok self-retracting lifeline is mandatory.\nHarness and inertia reel to be certified and tested prior to use.\nInertia reel to be secured to solid structure at all times.\nTool Box Talk to be carried out prior to work start.\nCorrect PPE to be worn at all times.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Dropped objects.", ar: '' },
        effect: { en: "Possible fatality.\nMajor injury.\nDamage to equipment.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Any tools and equipment not in use to be stored safely and secured.\nArea below worksite to have barriers and signs posted.\nToe / kicker boards to be installed on all scaffolding.\nAny loose objects and materials to be removed from platform.\nGood housekeeping to be maintained at all times.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Weather conditions.", ar: '' },
        effect: { en: "Possible fatality.\nHeat stress / hypothermia, leading to loss of senses and possible serious incident.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Under no circumstances shall personnel work during high winds.\nIssuing Authority to obtain weather information and update on a regular basis.\nOnly the Issuing Authority can authorize a return to work after weather conditions subside.\nIf weather conditions deteriorate during task and become unsafe, stop the job and return permit to office.\nPA to ensure that all personnel have left the worksite.\nDuring periods of high temperatures personnel to ensure that they have suitable supplies of drinking water.\nPersonnel to take regular breaks.\nPA to contact Issuing Authority for weather updates.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Working in noisy environment.", ar: '' },
        effect: { en: "Hearing loss / deafness, leading to confusion and possible serious incident.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Ear defenders or ear plugs to be worn at all times.\nPersonnel to comply with ear protection in designated areas of plant.\nCorrect PPE to be worn at all times.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Site alarm.\nAll personnel to muster.", ar: '' },
        effect: { en: "Slips / Trips / Falls.\nSerious injury.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Personnel are to ensure that all equipment is de-energized and hoses to be depressurized prior to leaving worksite.\nAll personnel to be accounted for prior to leaving worksite.\nAll personnel to proceed to their muster points in a safe and orderly manner.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
    ],
  },
  {
    category: { en: "Confined Space Entry Operation", ar: "الدخول إلى الأماكن المحصورة" },
    items: [
      {
        hazard: { en: "Inadequate preparation.", ar: '' },
        effect: { en: "Personal injury.\nPossible fatalities.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Only competent and trained personnel to carry out the task.\nAqueous tank to be drained / flushed / purged until rid of all hydrocarbons / aqueous residues.\nUse correct PPE at all times.\nManway doors to be opened to assist with ventilation of vessel.\nRegular gas testing to be carried out until allowable levels are met.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'B',
      },
      {
        hazard: { en: "Inadequate isolation.", ar: '' },
        effect: { en: "Personal injury.\nFatality.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Only competent and trained personnel to carry out the task.\nIsolations to be carried out as per PTW procedure and adhered to.\nIsolations to be applied as per marked up P&ID. Valves to be locked and tagged.\nPositive isolations to be applied as per marked up P&ID.\nAll blinds to be tagged and entered in the blind list register.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'B',
      },
      {
        hazard: { en: "Confined space entry.", ar: '' },
        effect: { en: "Serious personal injury.\nPossible fatality.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Adhere to Confined Space Entry procedure PR-HSE-60.\nGood communication to be maintained at all times during task.\nOnly competent and trained personnel to carry out the task.\nOnly medically checked and fit persons to enter the confined space.\nMedical check certificate required prior to issuing the permit.\nAll confined space entry will be under the control of a Permit to Work and adhered to at all times.\nGas / atmosphere testing to be carried out prior to entry and recorded on the atmosphere test sheet.\nContinuous gas testing to be carried out whilst in tank.\nRescue equipment and trained users to be on location.\nRescue personnel to have been trained in the use of breathing apparatus.\nRescue plan discussed by all parties involved in confined space entry and approved rescue plan to be with permit.\nHarnesses and lifelines to be worn at all times during task by persons entering the vessel and lifeline secured with the standby man.\nStandby man must have a radio to communicate with CCR at all times.\nRadio channel to be discussed and agreed by all parties.\nCorrect PPE to be worn at all times.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'B',
      },
      {
        hazard: { en: "Access and egress.", ar: '' },
        effect: { en: "Major injury.\nSerious injury.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Suitable scaffold platform in place to aid personnel entering and exiting tank.\nScaffolding to be certified and displaying valid Scafftag.\nAny hoses and cables to be routed safely to avoid restricted access and egress.\nGood housekeeping at all times.\nGood communications at all times with personnel in confined space.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'B',
      },
      {
        hazard: { en: "Use of temporary lights.", ar: '' },
        effect: { en: "Serious injury to person.\nPossible fatality.\nFire and explosion.\nDamage to equipment.\nAsset damage.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Temporary lighting shall be low voltage (24V) Ex rated and inspected prior to use.\nTemporary lighting is certified and fit for purpose.\nAll temporary lighting to be registered in the Temporary Equipment Log Book.\nPR-HSE-66 Control of Temporary Portable Equipment procedure to be adhered to at all times.\nAll lighting cables to have been inspected prior to use.\nAny cables showing signs of wear or damage are not to be used.\nAny defective cables are to be replaced with new.\nCables to be routed carefully inside vessel to allow safe access and egress at all times.\nAdequate firefighting equipment on location at all times.\nGas testing shall be carried out on a continuous basis.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'B',
      },
      {
        hazard: { en: "Over-exposure to and inhalation of toxic fumes.", ar: '' },
        effect: { en: "Serious injury to person.\nPossible fatality.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'B',
        ctrl: { en: "Confined space to be well ventilated and aired prior to entry.\nRegular breaks to be taken by the maintenance teams.\nContinuous gas / atmosphere monitoring to take place during task.\nAny changes in detector limits or alarms, the entrants must evacuate the confined space immediately.\nCorrect PPE to be worn at all times.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Oxygen deficiency.", ar: '' },
        effect: { en: "Serious injury to person.\nPossible fatality.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Vessel to be well ventilated and tested for oxygen levels prior to entry and continuously during task.\nAny changes to oxygen levels, the entrants must evacuate the vessel immediately.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'B',
      },
      {
        hazard: { en: "Manual handling.", ar: '' },
        effect: { en: "Back or limb strain.\nPulled muscle.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'B',
        ctrl: { en: "Use correct manual handling techniques at all times.\nUse portable lifting equipment if available.\nCorrect PPE to be worn at all times.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
    ],
  },
  {
    category: { en: "Crane Operations", ar: "عمليات الأوناش" },
    items: [
      {
        hazard: { en: "Vehicle access to site.", ar: '' },
        effect: { en: "Collision.\nDamage to equipment.\nAsset damage.\nPossible fatality.\nObstruction of other vehicles / access.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Permit to work to be issued before entry to site.\nDesignated access route for vehicles and machinery to work area.\nEscort required at security gate to accompany driver to area of lift if unfamiliar with site.\nCrane driver to adhere to site speed limits and road signs.\nVehicles to be fitted with reversing alarms and flashing beacons.\nFlame arrestor to be fitted to diesel engine equipment.\nVehicles to be inspected before entering site and should be certified and fit for purpose.\nBanksman / flagman to escort vehicle / machinery on site.\nSuitable firm ground to be identified for crane to extend stability arms.\nArea to be worked in shall be barriered off with tape and warning signs to be posted.\nAdhere to PTW instructions at all times.\nEnsure area to be worked in is identified with approved drawings.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Potential overloading.", ar: '' },
        effect: { en: "Damage to equipment.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Crane pre-checks to be completed by a competent person prior to work start.\nCrane to have in-date certificate for use.\nAt no time shall the operator attempt to lift or move a load which is outside the capabilities of the crane.\nAll loads to be suitably marked with SWL which shall not be exceeded.\nAll loads to be lifted as per the crane operating envelope.\nToolbox talk to be held prior to work start.\nA signed-up lifting plan is to be issued by a certified person.\nAll slinging equipment shall be certified and examined for damage prior to being used; current certification certificates are required at all times.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Potential collision.", ar: '' },
        effect: { en: "Possible fatality.\nDamage to equipment.\nAsset damage.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Crane pre-checks to be completed by a competent person prior to work start.\nClear vision at all times whilst swinging, lifting and lowering boom.\nAdditional banksman to have clear view of crane boom and object to be lifted.\nGood communications by radio and hand signals at all times.\nTool Box Talk to be held prior to work start.\nA signed-up lifting plan is to be issued by a certified person.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Operator error.", ar: '' },
        effect: { en: "Possible fatality.\nDamage to equipment.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Only qualified crane operators shall be used to operate cranes and shall have had full training in the safe working practices and operating procedures.\nA competent banksman to be used when vision is restricted.\nUnder no circumstances shall personnel walk below a lifting operation.\nThe banksman shall remain in sight of the crane driver during lifting operations.\nOperators shall ensure that suitable observation of the task in hand is maintained at all times.\nGood communications by radio and visible hand signals at all times.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Banksman visibility.", ar: '' },
        effect: { en: "Injury to personnel.\nDamage to equipment.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'B',
        ctrl: { en: "Additional banksman to be used to ensure that lifting of load is always visible and that banksman has radio contact with crane operator.\nEnsure no lift is performed until the banksman has clear visibility.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Dropped objects.", ar: '' },
        effect: { en: "Injury to personnel.\nDamage to equipment.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Only competent personnel to carry out the task.\nTools to be secured whilst lifting to area of work.\nUse correct manual handling techniques.\nLifting equipment to be inspected prior to operation.\nArea to be barriered off.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Adverse weather.", ar: '' },
        effect: { en: "Personal injury.\nDamage to plant / equipment.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "No lifting operations to be performed during high wind speeds.\nEnsure personnel regularly rested or rotated during extreme hot / cold conditions.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
    ],
  },
  {
    category: { en: "Fork Lift Truck Operations", ar: "عمليات الرافعة الشوكية" },
    items: [
      {
        hazard: { en: "Incorrect destination of forklift.\nVehicle arrives in hazardous area of plant.", ar: '' },
        effect: { en: "Collision.\nDamage to equipment.\nAsset damage.\nPossible fatality.\nObstruction of other vehicles / access.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Forklift to be met at security gate and escorted by production personnel to designated area.\nVehicle route to have been discussed and agreed by relevant parties.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Plant and equipment impact.", ar: '' },
        effect: { en: "Possible fatality.\nAsset damage.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Toolbox Talk.\nQualified competent forklift driver to operate equipment.\nQualified personnel to manoeuvre and guide forklift operations.\nCorrect PPE to be worn at all times.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Plant and equipment impact during lifting.", ar: '' },
        effect: { en: "Serious personal injury.\nAsset damage.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Correct PPE to be worn at all times.\nTraining.\nProper inspected lifting gear used.\nInspection of lifting gear prior to starting the job.\nInspection of forklift trucks.\nCompetent forklift driver to be aware of personnel whilst lifting operations take place.\nForks shall be angled correctly during all lifting operations.\nDriver to ensure that load is stable and secure before manoeuvring lift.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Overload / defective due to mechanical failure.\nLoss of control.", ar: '' },
        effect: { en: "Asset damage.\nDamage to equipment.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Forklift trucks shall be in good mechanical condition.\nNo hydraulic leaks or slippage allowed.\nForklift truck commissioning pre-checks to be carried out and all safety systems to be operational.\nCertified lifting equipment to be used only.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Falling objects.", ar: '' },
        effect: { en: "Possible fatality.\nAsset damage.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "No work to take place above area of lift.\nBarriers to be used.\nHand tools to be secured when not in use.\nCorrect PPE. Safety helmets.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Greasy surfaces.\nLoss of vehicle control.", ar: '' },
        effect: { en: "Possible fatality.\nSlips / trips / falls.\nDamage to equipment.\nAsset damage.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Good housekeeping in area of work at all times.\nTools and equipment not in use to be removed from area.\nForklift driver to take extreme care during manoeuvres.\nForklift driver to avoid over-steering vehicle with load.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Overload / defective due to mechanical failure.", ar: '' },
        effect: { en: "Damage to equipment.\nAsset damage.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Forklift inspected prior to task.\nLoad to be assessed for acceptability prior to lift.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Incorrect destination of forklift.\nVehicle leaves in hazardous area of plant.", ar: '' },
        effect: { en: "Collision.\nDamage to equipment.\nAsset damage.\nPossible fatality.\nObstruction of other vehicles / access.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "On completion of task forklift to be escorted from plant to outside perimeter gates at security point by production personnel.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Manual handling.", ar: '' },
        effect: { en: "Injury to personnel.\nCuts and abrasions.\nMinor injuries to personnel.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Use correct manual lifting techniques.\nUsing safe working methods in carrying out the job.\nUse of suitable equipment for task.\nCorrect PPE to be worn at all times.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
    ],
  },
  {
    category: { en: "Scissor Lift Operations", ar: "عمليات الرافعة المقصية" },
    items: [
      {
        hazard: { en: "Incorrect destination of scissor lift vehicle.", ar: '' },
        effect: { en: "Vehicle arrives in hazardous area of plant.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Scissor lift vehicle to be met at security gate and escorted by production personnel to designated area.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Personnel at risk of being thrown from the scissor lift platform.", ar: '' },
        effect: { en: "Serious personal injury.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Toolbox Talk.\nCompetent scissor lift driver.\nPersonnel shall at all times when the machine is in motion and/or operation wear a full body safety harness with the lanyard attached to the anchorage point on the vehicle platform.\nCorrect PPE to be worn at all times.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Plant and equipment impact.", ar: '' },
        effect: { en: "Serious personal injury.\nAsset damage.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Emergency response training conducted for the security person.\nDrill scenario to be carried out periodically.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Overload / defective due to mechanical failure.\nLoss of control.", ar: '' },
        effect: { en: "Personal injury.\nAsset damage.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Scissor lift vehicle shall be in good mechanical condition.\nNo hydraulic leaks or slippage allowed.\nVehicle commissioning pre-checks to be carried out and all safety systems to be operational.\nCertified lifting equipment to be used only.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Vehicle at risk of overturning should the ground conditions be unstable.", ar: '' },
        effect: { en: "Serious personal injury.\nAsset damage.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Ensure at all times that where any vehicle is expected to operate, the ground conditions are compacted and suitable to support the weight of the vehicle when travelling and while in operation.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Falling objects.", ar: '' },
        effect: { en: "Personal injury.\nAsset damage.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Barriers to be used.\nHand tools to be secured when not in use.\nCorrect PPE. Safety helmets.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Incorrect destination of scissor lift vehicle.", ar: '' },
        effect: { en: "Vehicle leaves in hazardous area of plant.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "On completion of task scissor lift to be escorted from plant to outside perimeter gates at security point.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Greasy surfaces.\nSlips / trips / falls.", ar: '' },
        effect: { en: "Injury to personnel.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Good housekeeping in area of work at all times.\nTools and equipment not in use to be removed from area.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Manual handling.", ar: '' },
        effect: { en: "Injury to personnel.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Use correct manual lifting techniques.\nUsing safe working methods in carrying out the task.\nUse of suitable equipment for the task.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Incorrect use of PPE.", ar: '' },
        effect: { en: "Cuts and abrasions.\nMinor injuries to personnel.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Use of correct PPE at all times.\nOnly use PPE suitable for the task.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
    ],
  },
  {
    category: { en: "Digital Camera, Video Camera, Thermal Camera + Laser & Laptop Usage on Site", ar: "استخدام الكاميرات والليزر والحاسب المحمول في الموقع" },
    items: [
      {
        hazard: { en: "Ignition source from digital camera, video camera and / or laptop usage.", ar: '' },
        effect: { en: "Explosion / fire.\nPersonal injury / fatality.\nPlant / equipment damage.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "PTW to be issued prior to using digital camera, video camera and / or laptop.\nPersonnel to have site induction prior to site visit.\nContinuous gas monitoring to be in use.\nPersonnel to be familiar with gas monitoring equipment.\nDigital camera, video camera and / or laptop NOT TO BE USED in event of gas monitoring alarm.\nHSE technician or nominated person to accompany personnel whilst on site.\nTBT to include area of usage.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Use of camera flash / laser.", ar: '' },
        effect: { en: "Activation of UV / IR flame detectors on plant.\nLoss of production.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'B',
        ctrl: { en: "Personnel to familiarise themselves with the function of the equipment to prevent incorrect use.\nCorrect settings without flash facility on camera to be used at all times.\nBattery change-out NOT to be performed on site.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Slips, trips, falls.", ar: '' },
        effect: { en: "Personal injury - cuts and abrasions.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'B',
        ctrl: { en: "Use approved walkways.\nEnsure access / egress routes are clear.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
    ],
  },
  {
    category: { en: "Diving Operations (Splash Zone / Underwater Inspection)", ar: "عمليات الغوص (منطقة الرذاذ / الفحص تحت الماء)" },
    items: [
      {
        hazard: { en: "Equipment not fit for purpose.", ar: '' },
        effect: { en: "Possible fatality.\nDamage to equipment.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "All diving equipment to be certified and tested prior to use.\nOnly suitable diving equipment shall be used for the task.\nPre-dive checks shall be carried out at all times.\nSurface equipment shall be monitored at all times by trained and competent personnel.\nEquipment showing any signs of wear or damage is to be replaced with new.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Diving operations (depth of dive no greater than 3 metres).\nVisual inspection.\nMeasuring marine growth using a roller device.", ar: '' },
        effect: { en: "Possible fatality.\nMajor injuries caused by propeller blades.\nDamage to equipment.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "All diving equipment to be certified and tested prior to use.\nZodiac craft on location at all times to aid divers.\nStandby diver present at all times on Zodiac craft.\nEnsure that diver’s marker buoy is located in area of diver.\nUse of radio communications where possible.\nUse of rope pulling signals to warn diver to abort the dive.\nGood communications maintained from diving vessel to other shipping in area.\nPlatform to ensure that no work activities take place above area of divers at all times during task.\nTool Box Talk.\nDiving operations personnel to keep watch for vessels getting too close to diving ops.\nAdhere to diving zones stipulated in work scope / method statement / procedure.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Use of digital camera.\nVisual inspection up to 5 metres above the water level.", ar: '' },
        effect: { en: "Fire / explosion.\nPossible fatality.\nSerious / major injury.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Camera to be inspected prior to use.\nPersonnel to operate camera shall ensure that they fully understand all the functions prior to use.\nIf camera is showing any signs of wear or damage it shall not be used and must be replaced with new.\nPersonnel not familiar with gas testing equipment must be accompanied by a HSE technician or nominated person at all times.\nContinuous gas testing required in area of inspection.\nArea / zone for camera operation to be discussed at permit meeting with Issuing Authority and HSE.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Diver in collision with sea vessel.", ar: '' },
        effect: { en: "Possible fatality.\nMajor injuries caused by propeller blades.\nDamage to equipment.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Flag on vessel to highlight that there are diving operations in progress.\nEnsure that diver’s marker buoy is located in area of diver.\nUse of radio communications where possible.\nUse of rope pulling signals to warn diver to abort the dive.\nGood communications maintained from diving vessel to other shipping in area.\nTool Box Talk.\nDiving operations personnel to keep watch for vessels getting too close to diving ops.\nAdhere to diving zones stipulated in work scope / method statement / procedure.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Encountering obstacles due to poor visibility underwater.", ar: '' },
        effect: { en: "Possible fatality.\nEntanglement.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Divers to carry waterproof torches or lamps at all times during poor visibility.\nUse of buddy system.\nDivers to move slowly to maintain visibility with others.\nIn case of entanglement, diver to remain calm and wait for assistance.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Diver out of air.", ar: '' },
        effect: { en: "Possible fatality.\nAsphyxiation.\nDrowning.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Ensure that pre-dive checks are carried out at all times.\nEnsure that bottle pressure gauge is calibrated on a regular basis.\nRegular gauge checks to be carried out by divers.\nCarry adequate supplies.\nUse of buddy system techniques.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Equipment failure.", ar: '' },
        effect: { en: "Possible fatality.\nDamage to equipment.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "All diving equipment shall be checked prior to use. Any suspect equipment shall be replaced with new.\nUse the bail-out cylinder emergency system.\nUse the pneumo in case of bail-out failure.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Loss of contact / communication between divers.", ar: '' },
        effect: { en: "Loss of crucial dive time.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Divers to maintain visual contact at all times.\nIf loss of contact occurs, carry out a 30 second search and then surface (part of pre-dive brief).\nLocate diver buoy.\nStandby diver available at all times during operations.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Poor communication between divers of different nationality.", ar: '' },
        effect: { en: "Low achievement levels.\nPoor pre-dive briefs.\nTool Box Talk not communicated.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Ensure good quality pre-dive briefs.\nTool Box Talk translated to different languages. Use of interpreter.\nDraw sketches of diving requirements.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Platform emergency / hydrocarbon release / condensate sea contamination.", ar: '' },
        effect: { en: "Fire / explosion.\nPossible fatality.\nDamage to equipment.\nAsset damage.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Good communications maintained at all times between the diving vessel and the platform.\nAny signs of process upset or emergency, the CCR shall notify the diving vessel immediately.\nRescue plan to be discussed by all relevant parties and then documented.\nIsolations in place on platform manual dump valves.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
    ],
  },
  {
    category: { en: "Use of Temporary Portable Equipment", ar: "استخدام المعدات المؤقتة المتنقلة" },
    items: [
      {
        hazard: { en: "Engine driven generators / portable welding equipment / air compressors / pressure wash equipment / electrical hand tools / pneumatic power tools / hydraulic equipment / lighting / hoses etc.", ar: '' },
        effect: { en: "Ignition sources leading to explosion and / or fire.\nPossible fatality.\nPersonal injury.\nDamage to equipment.\nDamage to asset.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Adhere to the procedure for Control of Temporary Portable Equipment RPC-MS-OPS-PTW-418.\nAll temporary portable equipment to be registered in the Temporary Portable Equipment Log Book.\nLog Book to be kept and maintained by nominated persons.\nAll equipment to be certified and tested prior to entering worksite.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Equipment certification / inspection.", ar: '' },
        effect: { en: "Ignition sources leading to explosion and / or fire.\nPossible fatality.\nPersonal injury.\nDamage to equipment.\nDamage to asset.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Ensure that all equipment is inspected by Rashpetco personnel and tagged.\nUnder no circumstances shall equipment be allowed on site without an inspection tag.\nResponsible person for equipment to ensure that all documentation / certification and equipment are available 48 hours prior to use.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Internal combustion engines in hazardous areas.", ar: '' },
        effect: { en: "Ignition sources leading to explosion and / or fire.\nPossible fatality.\nPersonal injury.\nDamage to equipment.\nDamage to asset.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Combustion engine / equipment shall meet the design specification required for the area / zone.\nThe equipment shall be clearly marked \"suitable for use in hazardous areas zones 1 & 2\" or \"non-hazardous areas\".\nSpark arrestors shall be fitted to all internal combustion engines operating in a hazardous area.\nPetrol and LPG engines shall not be used in process plant facilities.\nSite the machine to prevent exhaust fumes from entering confined spaces of work.\nDuring engine running operations a standby man shall be on location at all times and trained to stop the engine if required.\nContinuous gas monitoring shall be carried out by standby man.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Rotating and / or moving parts on equipment.", ar: '' },
        effect: { en: "Ignition sources leading to explosion and / or fire.\nPossible fatality.\nPersonal injury.\nDamage to equipment.\nDamage to asset.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Ensure that sufficient information is gathered for equipment e.g. operating instructions / procedures / method statements / training requirements for personnel.\nRotating and moving parts to have protective guards / cages to prevent injury to personnel.\nTool Box Talk.\nCorrect PPE to be worn specific to task and equipment being used.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Electrical hand tools.", ar: '' },
        effect: { en: "Ignition sources leading to explosion and / or fire.\nPossible fatality.\nPersonal injury.\nDamage to equipment.\nDamage to asset.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Equipment must be suitable for the task.\nElectrical hand tools shall be in good working condition and regularly inspected / tested and certified.\nCheck integrity of all electrical connections.\nEnsure that the equipment is of the correct voltage for supply at the worksite.\nIf non-Ex equipment, continuous gas monitoring during task.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Pneumatic / hydraulic equipment.", ar: '' },
        effect: { en: "Possible fatality.\nPersonal injury.\nDamage to equipment.\nDamage to asset.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Equipment must be suitable for the task.\nEnsure that any pressure relief systems are inspected and certified.\nEnsure that hoses and connections are fit for purpose.\nPressure rated hoses must have valid certification.\nIf unit is connected to ESD system ensure that function tests are carried out to prove shutdown.\nUnits and equipment to be checked for oil leakage.\nPneumatic equipment must have the maximum working pressure identified on it.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Mechanical lifting equipment.", ar: '' },
        effect: { en: "Possible fatality.\nPersonal injury.\nDamage to equipment.\nDamage to asset.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Equipment must be suitable for the task.\nEquipment used for lifting activities to have valid certification and coding.\nEnsure that lifting equipment is rated for the task.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Use of flexible hoses.", ar: '' },
        effect: { en: "Ignition sources leading to explosion and / or fire.\nPossible fatality.\nPersonal injury.\nDamage to equipment.\nDamage to asset.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Hoses shall be rated specific for the task.\nHoses shall be in good working condition and regularly inspected / tested and certified.\nHoses to be rated against static electricity build up.\nHoses containing high pressure are to be secured against accidental release.\nHoses to have correct fittings for task.\nAll hoses to be fitted with whip checks.\nAny hoses showing signs of wear or damage shall be replaced and old ones discarded.\nHoses to be correctly stored whilst not in use.\nAll hoses must be removed from process pipework on completion of task or prior to the introduction of hydrocarbons.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Ignition source (temporary lights).", ar: '' },
        effect: { en: "Serious injury to person.\nPossible fatality.\nFire and explosion.\nDamage to equipment.\nAsset damage.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Temporary lighting shall be low voltage Ex rated and inspected prior to use.\nTemporary lighting is certified and fit for purpose.\nAll temporary lighting to be registered in the Temporary Equipment Log Book.\nAll lighting cables to have been inspected prior to use.\nAny cables showing signs of wear or damage are not to be used.\nAny defective cables are to be replaced with new.\nCables to be routed away from walkways to allow safe access and egress at all times.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Impact on utility and emergency systems.", ar: '' },
        effect: { en: "Loss of production.\nAsset damage.", ar: '' },
        severityBefore: 3, likelihoodBefore: 'C',
        ctrl: { en: "Ensure that plant facilities can support temporary portable equipment.\nESD loops / tie-ins to temporary portable equipment to be proved / tested against cause and effect diagrams.", ar: '' },
        severityAfter: 3, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Re-fuelling diesel driven equipment.", ar: '' },
        effect: { en: "Ignition sources leading to explosion and / or fire.\nPossible fatality.\nPersonal injury.\nDamage to equipment.\nDamage to asset.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Re-fuelling shall be avoided where possible in hazardous areas.\nSite the machine as far away as possible from the hazardous area.\nEnsure that the engine is shut down during re-fuelling.\nProvide a bund to capture spills to prevent environmental issues.\nEnsure that re-fuelling hoses are in good condition and showing no signs of leakage.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Maintaining equipment on site.", ar: '' },
        effect: { en: "Ignition sources leading to explosion and / or fire.\nPossible fatality.\nPersonal injury.\nDamage to equipment.\nDamage to asset.", ar: '' },
        severityBefore: 4, likelihoodBefore: 'C',
        ctrl: { en: "Equipment to be closely monitored for efficiencies and deficiencies in performance.\nRegular checks to be carried out on engine temperatures and oil pressures (where applicable).\nInspect unit for signs of oil leakage / coolant / hose condition.\nIf anomalies on equipment are found, it shall be stopped and investigated by trained and competent personnel.\nIf onsite repairs are required to equipment, a permit shall be raised to carry out the task.", ar: '' },
        severityAfter: 4, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Poor housekeeping.", ar: '' },
        effect: { en: "Injury to personnel.\nSlips / Trips / Falls.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'B',
        ctrl: { en: "Any equipment that is not being used or required to be removed to a safe area away from work activities or off site.\nAll hoses and cables to be routed away from access walkways.\nEquipment must not obstruct Fire and Gas systems.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
      {
        hazard: { en: "Site emergency.\nAll personnel to muster.", ar: '' },
        effect: { en: "Injury to personnel.\nSlips / Trips / Falls.", ar: '' },
        severityBefore: 2, likelihoodBefore: 'C',
        ctrl: { en: "Emergency \"Stops\" on all running equipment shall be clearly marked.\nAll personnel are to make safe their equipment by de-energizing or depressurizing hoses prior to leaving worksite.\nPersonnel to report to their designated muster points in an orderly manner.", ar: '' },
        severityAfter: 2, likelihoodAfter: 'A',
      },
    ],
  },
];