name: Build PTW

on:
  workflow_dispatch:        # manual trigger from GitHub UI
  push:
    tags:
      - 'v*'               # auto-trigger on version tags like v1.0.0

jobs:

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'          # caches pip downloads across runs

      - name: Cache Nuitka
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\Nuitka\Nuitka
          key: nuitka-windows-${{ hashFiles('client/**/*.py') }}
          restore-keys: nuitka-windows-

      - name: Install dependencies
        run: pip install nuitka pyqt6 qtawesome reportlab pillow qrcode requests pypdf openpyxl bcrypt keyring

      - name: Build
        run: >
          python -m nuitka
          --onefile
          --assume-yes-for-downloads
          --show-progress
          --enable-plugin=pyqt6
          --include-data-dir=assets=assets
          --include-data-dir=fonts=fonts
          --windows-icon-from-ico=assets/sh-logo-trans.ico
          --windows-console-mode=disable
          --output-filename=PTW.exe
          main.py

      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: client/PTW.exe


  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'          # caches pip downloads across runs

      - name: Cache Nuitka
        uses: actions/cache@v4
        with:
          path: ~/.cache/Nuitka
          key: nuitka-linux-${{ hashFiles('client/**/*.py') }}
          restore-keys: nuitka-linux-

      - name: Install system dependencies
        run: sudo apt-get install -y patchelf libgl1 libegl1

      - name: Install dependencies
        run: pip install nuitka pyqt6 qtawesome reportlab pillow qrcode requests pypdf openpyxl bcrypt keyring

      - name: Build
        run: >
          python -m nuitka
          --onefile
          --assume-yes-for-downloads
          --show-progress
          --enable-plugin=pyqt6
          --include-data-dir=assets=assets
          --include-data-dir=fonts=fonts
          --linux-onefile-icon=assets/sh-logo-trans.png
          --output-filename=PTW
          main.py

      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: client/PTW
